### PR TITLE
Suggested revisions to code organization

### PR DESCRIPTION
**Pull request by smurthys**
Here is a summary of the changes I suggest through this PR. The line numbers shown below are from the revised file.

- File prologue: Include a high-level problem statement and a URL to the actual problem definition.

- General: use `const` where possible. Please start a SIGCPP thread so we can discus this point further

- L9: Space before `<iostream>`

- L17: variable sum is now declared and initialized at the latest point possible

- L19: use qualified name `std::cout` instead of inserting a qualified name earlier with a `using` declaration. The name `cout` is used only once.

Open questions: The algorithm/strategy is unclear. Specifically, variable names `N` and `M` do not communicate their purpose. These variables names need to be revised to match what they represent. Also, a comment is needed to explain the algorithm/strategy.

### CODE REVIEW

**Comment by Ajetski** [comment]
@smurthys you have removed the return statement, but main is still an int function, not void. Is this a good practice? I was under the impression that the first is the best practice:
```C++
int main(){
    return 0;
}
```
and
```C++
void main(){
}
```
It is entirely possible that it will return 0 by default and I am overthinking this.

**Comment by Ajetski** [comment]
Secondly, I believe that the calculation itself is currently incorrect. You have smartly used a the summation formula for 1 to n, and modifying it to compute the summation of the multiples of 3 and 5. You are adding the result of these two summations together to obtain the result. This will result in an error, as the result will be greater than the desired output by computing the multiples of 15 twice. These multiples of 15 will be added as part of each calculation and then included in the final sum. To reconcile this, we can compute the sum of the multiples of 15 and subtract them once.

For example, consider the multiples of 3 and 5 up to 35.
Multiples of 3:
3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33
Multiples of 5:
5, 10, 15, 20, 25, 30, 35

If we add up the sum of these two series, the result will include 15 and 30 twice.

**Comment by smurthys** [comment]
Per C++ standard ([basic.start.main](https://timsong-cpp.github.io/cppwp/n4659/basic.start.main#5)), it is OK for `main` to exclude a `return` statement . As @Ajetski surmises, the missing `return` statement causes the function to return 0. There is no "best practice" as such about this (but it might be best to check Core Guidelines), but it is very common to exclude `return` from `main` when the exact returned value does not matter.

As the PR's heading says, this PR focuses only on code organization; not on code correctness. The issue of correctness is couched in the "open questions" part of the PR message.

BTW, one of the SIGCPP team members has previously pointed out the issue of duplicate terms.

**Comment by smurthys** [comment]
@frost00 After you dispose of this PR, I suggest renaming the repo to `euler-cpp` or such to reflect its purpose. I also recommend adding a (simple) README.

**Comment by smurthys** [comment]
BTW, the standard disallows `void main()`. Specifically, `main` should always return `int` ([basic.start.main](https://timsong-cpp.github.io/cppwp/n4659/basic.start.main#2))

**Pull request merged**
